name: $hd_search

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'hd/search'
        modules: 'app'
    
    - uses: hyoo-ru/gh-deploy@mater
      if: github.ref == 'refs/heads/master'
      with:
        site-directory: 'hd/search/app/-'
